export const CONSTANTS = {
    MOUSE_ROTATION_SPEED: 0.01,
    MAX_LAYERS: 10,
    MAX_CLOUD_LAYERS: 10,
    MAX_CLOUD_OFFSET: 0.0015,
    MIN_PHI: 0.1,
    MAX_PHI: Math.PI - 0.1,
    AUTO_ROTATE: false,
    LEFT_BUTTON_VALUE: 0,
    PLANET_ROTATION_SPEED: 0.02,
    MOVE_ACCELERATION: 0.001,
    TURN_ACCELERATION: 0.005,
    FRICTION_MOVE: 0.95,
    FRICTION_TURN: 0.90,

};