export function getCanvasElement() {
    return document.querySelector("#glcanvas");
}

export function getControlsElements() {
    return {
        controlsToggle:     document.getElementById('controls-toggle'),
        controlsPanel :     document.getElementById('controls'),
        controlsClose :     document.getElementById('controls-close'),
        seedInput     :     document.getElementById('seed-input'),
        seedRandomBtn :     document.getElementById('seed-random'),
        noiseTypeSelect:    document.getElementById('noise-type'),
        subdivisionsSlider: document.getElementById('subdivisons'),
        subdivisionsValue:  document.getElementById('subdivisons-value'),
        octavesSlider:      document.getElementById('octaves'),
        octavesValue:       document.getElementById('octaves-value'),
        persistenceSlider:  document.getElementById('persistence'),
        persistenceValue:   document.getElementById('persistence-value'),
        lacunaritySlider:   document.getElementById('lacunarity'),
        lacunarityValue:    document.getElementById('lacunarity-value'),
        noiseZoomSlider:    document.getElementById('noise-zoom'),
        noiseZoomValue:     document.getElementById('noise-zoom-value'),
        wireframeToggle:    document.getElementById('wireframe-toggle'),
        cloudsToggle:       document.getElementById('clouds-toggle'),
        lightSpeed:         document.getElementById('light-speed'),
        lightSpeedValue:    document.getElementById('light-speed-value'),
        lightBrightness:    document.getElementById('light-brightness'),
        lightBrightnessValue:    document.getElementById('light-brightness-value'),
        lambertianDiffuseToggle: document.getElementById('lambertian-toggle'),
        rimIntensity:         document.getElementById('rim-intensity'),
        rimIntensityValue:    document.getElementById('rim-intensity-value'),
        rimColor:             document.getElementById('rim-color'),
        rimColorValue:        document.getElementById('rim-color-value'),
        rimToggle:            document.getElementById('rim-toggle'),
        waterOpacity:         document.getElementById('water-opacity'),
        waterOpacityValue:    document.getElementById('water-opacity-value'),
        waterToggle:         document.getElementById('water-toggle'),
        wavesToggle:         document.getElementById('waves-toggle'),
        cloudSpeed:              document.getElementById('cloud-speed'),
        cloudSpeedValue:         document.getElementById('cloud-speed-value'),
        cloudOpacity:            document.getElementById('cloud-opacity'),
        cloudOpacityValue:       document.getElementById('cloud-opacity-value'),
        cloudWarpIntensity:      document.getElementById('cloud-warp-intensity'),
        cloudWarpIntensityValue: document.getElementById('cloud-warp-intensity-value'),
        cloudWarpTime:           document.getElementById('cloud-warp-time'),
        cloudWarpTimeValue:      document.getElementById('cloud-warp-time-value'),
        cloudThreshold:          document.getElementById('cloud-threshold'),
        cloudThresholdValue:     document.getElementById('cloud-threshold-value'),
        cloudAlpha:              document.getElementById('cloud-alpha'),
        cloudAlphaValue:         document.getElementById('cloud-alpha-value'),
        cloudColor:              document.getElementById('cloud-color'),
        cloudColorValue:         document.getElementById('cloud-color-value'),
        cloudTextureZoom:        document.getElementById('cloud-texture-zoom'),
        cloudTextureZoomValue:   document.getElementById('cloud-texture-zoom-value'),
        terrainDisplacement:     document.getElementById('terrain-displacement'),
        terrainDisplacementValue:document.getElementById('terrain-displacement-value'),
        numLayersSlider:         document.getElementById('num-layers'),
        numLayersValue: document.getElementById('num-layers-value'),
        layer0Slider:   document.getElementById('layer0-level'),
        layer1Slider:   document.getElementById('layer1-level'),
        layer2Slider:   document.getElementById('layer2-level'),
        layer3Slider:   document.getElementById('layer3-level'),
        layer4Slider:   document.getElementById('layer4-level'),  
        layer5Slider:   document.getElementById('layer5-level'),  
        layer6Slider:   document.getElementById('layer6-level'),  
        layer7Slider:   document.getElementById('layer7-level'),  
        layer8Slider:   document.getElementById('layer8-level'),  
        layer9Slider:   document.getElementById('layer9-level'),  
        layer0Value:    document.getElementById('layer0-value'),
        layer1Value:    document.getElementById('layer1-value'),
        layer2Value:    document.getElementById('layer2-value'),
        layer3Value:    document.getElementById('layer3-value'),
        layer4Value:    document.getElementById('layer4-value'),
        layer5Value:    document.getElementById('layer5-value'),
        layer6Value:    document.getElementById('layer6-value'),
        layer7Value:    document.getElementById('layer7-value'),
        layer8Value:    document.getElementById('layer8-value'),
        layer9Value:    document.getElementById('layer9-value'),
        layer0Color:    document.getElementById('layer0-color'),
        layer1Color:    document.getElementById('layer1-color'),
        layer2Color:    document.getElementById('layer2-color'),
        layer3Color:    document.getElementById('layer3-color'),
        layer4Color:    document.getElementById('layer4-color'),
        layer5Color:    document.getElementById('layer5-color'),
        layer6Color:    document.getElementById('layer6-color'),
        layer7Color:    document.getElementById('layer7-color'),
        layer8Color:    document.getElementById('layer8-color'),
        layer9Color:    document.getElementById('layer9-color'),
        addRingBtn:      document.getElementById('add-ring'),
        removeRingBtn:   document.getElementById('remove-ring'),
        ringCount:     document.getElementById('ring-count'),
    }
}